"""
This type stub file was generated by pyright.
"""

from typing import override

"""
This type stub file was generated by pyright.
"""
class InvalidMangaIdError(ValueError):
    """Raises if provided bad id in path params."""
    @override
    def __str__(self) -> str:
        ...
    


