"""
This type stub file was generated by pyright.
"""

from robyn import Robyn
from sqlalchemy.ext.asyncio import create_async_engine
from manga.infrastructure.db.conn import sqla_session_maker
from manga.presentation.api.config import Settings

def start_app(host: str = ..., port: int = ...): # -> None:
    """Startup application."""
    ...

def setup_app() -> Robyn:
    """Return Robyn application."""
    ...

