"""
This type stub file was generated by pyright.
"""

from typing import Annotated, ClassVar
from pydantic import PostgresDsn
from pydantic_settings import BaseSettings, SettingsConfigDict

"""
This type stub file was generated by pyright.
"""
class Settings(BaseSettings):
    """Main settings for manga service."""
    db_uri: PostgresDsn = ...
    test_mode: Annotated[bool, """
    Need for run application in separate procces with
    SQLAlchemy nested transactions.

    Required because Robyn has no support for running in tests.
    https://github.com/sparckles/Robyn/issues/507
    """,] = ...
    model_config: ClassVar[SettingsConfigDict] = ...


