"""
This type stub file was generated by pyright.
"""

from robyn import Response
from robyn.types import PathParams
from manga.presentation.api.di import GlobalDependencies

"""
This type stub file was generated by pyright.
"""
router = ...
@router.get("/:manga_id")
async def get_manga(path_params: PathParams, global_dependencies: GlobalDependencies) -> dict[str, int] | Response:
    """Return manga finded by id."""
    ...

