"""add new columns

Revision ID: 9d3ba6bc8775
Revises: 14af6205eb04
Create Date: 2025-09-10 15:55:58.039747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d3ba6bc8775"
down_revision: str | Sequence[str] | None = "14af6205eb04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "manga", sa.Column("title", sa.String(length=200), nullable=False)
    )
    op.add_column("manga", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("manga", "description")
    op.drop_column("manga", "title")
    # ### end Alembic commands ###
