"""add foreign key column

Revision ID: 14af6205eb04
Revises: e37e84f9c26e
Create Date: 2025-09-07 21:13:06.609025

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14af6205eb04"
down_revision: str | Sequence[str] | None = "e37e84f9c26e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chapters", sa.Column("manga_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "chapters", "manga", ["manga_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chapters", type_="foreignkey")
    op.drop_column("chapters", "manga_id")
    # ### end Alembic commands ###
