"""
This type stub file was generated by pyright.
"""

from collections.abc import Mapping
from dataclasses import dataclass
from enum import Enum
from typing import Final, Optional, Union

class ConnectionMode(Enum):
    bridge_ip = ...
    gateway_ip = ...
    docker_host = ...
    @property
    def use_mapped_port(self) -> bool:
        """
        Return True if mapped ports should be used for this connection mode.

        Mapped ports are used for all connection modes except 'bridge_ip'.
        """
        ...
    


def get_docker_socket() -> str:
    """
    Determine the docker socket, prefer value given by env variable

    Using the docker api ensure we handle rootless docker properly
    """
    ...

def get_bool_env(name: str) -> bool:
    """
    Get environment variable named `name` and convert it to bool.

    Defaults to False.
    """
    ...

TC_FILE = ...
TC_GLOBAL = ...
def get_user_overwritten_connection_mode() -> Optional[ConnectionMode]:
    """
    Return the user overwritten connection mode.
    """
    ...

def read_tc_properties() -> dict[str, str]:
    """
    Read the .testcontainers.properties for settings. (see the Java implementation for details)
    Currently we only support the ~/.testcontainers.properties but may extend to per-project variables later.

    :return: the merged properties from the sources.
    """
    ...

_WARNINGS = ...
@dataclass
class TestcontainersConfiguration:
    max_tries: int = ...
    sleep_time: int = ...
    ryuk_image: str = ...
    ryuk_privileged: bool = ...
    ryuk_disabled: bool = ...
    _ryuk_docker_socket: str = ...
    ryuk_reconnection_timeout: str = ...
    tc_properties: dict[str, str] = ...
    _docker_auth_config: Optional[str] = ...
    tc_host_override: Optional[str] = ...
    connection_mode_override: Optional[ConnectionMode] = ...
    @property
    def docker_auth_config(self) -> Optional[str]:
        ...
    
    @docker_auth_config.setter
    def docker_auth_config(self, value: str) -> None:
        ...
    
    def tc_properties_get_tc_host(self) -> Union[str, None]:
        ...
    
    @property
    def timeout(self) -> int:
        ...
    
    @property
    def ryuk_docker_socket(self) -> str:
        ...
    
    @ryuk_docker_socket.setter
    def ryuk_docker_socket(self, value: str) -> None:
        ...
    


testcontainers_config: Final = ...
__all__ = ["ConnectionMode", "testcontainers_config"]
_deprecated_attribute_mapping: Final[Mapping[str, str]] = ...
def __dir__() -> list[str]:
    ...

def __getattr__(name: str) -> object:
    """
    Allow getting deprecated legacy settings.
    """
    ...

