"""
This type stub file was generated by pyright.
"""

from testcontainers.core.container import DockerContainer

ADDITIONAL_TRANSIENT_ERRORS = ...
class DbContainer(DockerContainer):
    """
    **DEPRECATED (for removal)**

    Generic database container.
    """
    def get_connection_url(self) -> str:
        ...
    
    def start(self) -> DbContainer:
        ...
    


