"""
This type stub file was generated by pyright.
"""

from types import TracebackType
from typing import Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    ...
class Network:
    """
    Network context manager for programmatically connecting containers.
    """
    def __init__(self, docker_client_kw: Optional[dict[str, Any]] = ..., docker_network_kw: Optional[dict[str, Any]] = ...) -> None:
        ...
    
    @property
    def id(self) -> Optional[str]:
        ...
    
    def connect(self, container_id: str, network_aliases: Optional[list[str]] = ...) -> None:
        ...
    
    def remove(self) -> None:
        ...
    
    def create(self) -> Network:
        ...
    
    def __enter__(self) -> Network:
        ...
    
    def __exit__(self, exc_type: Optional[type[BaseException]], exc_val: Optional[BaseException], exc_tb: Optional[TracebackType]) -> None:
        ...
    


