"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

@dataclass(frozen=True, kw_only=True)
class MangaDTO:
    """Manga data-transfer object."""
    id: int
    ...


