"""
This type stub file was generated by pyright.
"""

from abc import abstractmethod
from typing import Protocol
from manga.application.dto import MangaDTO

"""Manga service repository interfaces."""
class Repository(Protocol):
    """Base repository protocol."""
    ...


class MangaRepository(Repository, Protocol):
    """Manga repository interface."""
    @abstractmethod
    async def get_by_id(self, manga_id: int) -> MangaDTO | None:
        """Search manga by provided id."""
        ...
    
    @abstractmethod
    async def get_all(self, limit: int = ..., offset: int = ...) -> list[MangaDTO]:
        """Return all mangas."""
        ...
    


