"""
This type stub file was generated by pyright.
"""

from manga.application.dto import MangaDTO
from manga.application.repository import MangaRepository

"""Manga application-layer service."""
class MangaService:
    manga_repo: MangaRepository
    def __init__(self, manga_repo: MangaRepository) -> None:
        ...
    
    async def get_manga_by_id(self, manga_id: int) -> MangaDTO:
        """
        Return finded manga by provided id.

        :param manga_id: Manga ID in persistence storage
        :return: Manga data-transfer object
        """
        ...
    
    async def get_all_manga(self) -> list[MangaDTO]:
        """Return all mangas in persistence storage."""
        ...
    


