services:
  auth_db:
    image: postgres:16.9-bookworm
    env_file: ".env"

  auth_service:
    build:
      context: ./services/auth_service/
    restart: on-failure
    ports: ["8001:80"]
    environment:
      - JWT__secret_key=abbbb
      - JWT__expire_minutes=10
      - DB__uri=$POSTGRES_DB_URI
    env_file: ".env"
