services:
  gateway:
    build:
      context: ./services/gateway/
    ports: ["8000:80"]
    profiles: [dev, prod]

  auth_service:
    extends:
      file: compose.override.yml
      service: auth_service
    profiles: [prod]
    depends_on:
      - auth_db

  auth_db:
    extends:
      file: compose.override.yml
      service: auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    profiles: [prod]

  auth_service_dev:
    extends:
      file: compose.override.yml
      service: auth_service
    volumes:
      - ./services/auth/src:/app/src
    command:
      [
        "uvicorn",
        "--factory",
        "src.auth.main:create_production_app",
        "--port",
        "80",
        "--host",
        "0.0.0.0",
        "--reload",
      ]
    profiles: [dev]
    depends_on:
      - auth_db_dev

  auth_db_dev:
    extends:
      file: compose.override.yml
      service: auth_db
    container_name: auth_db
    ports:
      - 5432:5432
    profiles: [dev]

volumes:
  auth_db_data:
