services:
  gateway:
    build:
      context: ./services/api_gateway/
    ports: ["8000:80"]

  auth_service:
    build:
      context: ./services/auth_service/
    depends_on:
      - auth_db
    ports: ["8001:80"]
    environment:
      - JWT__secret_key=abbbb
      - JWT__expire_minutes=10
      - DB__uri=$POSTGRES_DB_URI
    env_file: ".env"

  auth_db:
    image: postgres:16.9-bookworm
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    env_file: ".env"

volumes:
  auth_db_data:
