services:
  gateway:
    build:
      context: ./services/api_gateway/
    ports: ["8000:80"]
    profiles: [dev, prod]

  auth_service:
    extends:
      file: compose.override.yml
      service: auth_service
    profiles: [prod]

  auth_db:
    extends:
      file: compose.override.yml
      service: auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    profiles: [prod]

  auth_service_dev:
    extends:
      file: compose.override.yml
      service: auth_service
    volumes:
      - ./services/auth_service/src:/app/src
    command:
      [
        "/app/.venv/bin/uvicorn",
        "--factory",
        "src.auth_service:setup_app",
        "--port",
        "80",
        "--host",
        "0.0.0.0",
        "--reload",
      ]
    profiles: [dev]

  auth_db_dev:
    extends:
      file: compose.override.yml
      service: auth_db
    container_name: auth_db
    profiles: [dev]

volumes:
  auth_db_data:
