[tool.uv.workspace]
members = ["./services/api_gateway/", "./services/auth_service/"]

[dependency-groups]
lint = ["basedpyright==1.31.0"]

[tool.basedpyright]
include = ["services"]
exclude = ["**/__pycache__", "**/.venv", "**/migrations", "**/tests"]
ignore = ["**/*.lock"]
reportUnusedCallResult = false
reportAny = false

[tool.ruff]
target-version = "py313"
line-length = 80
extend-exclude = ["**/typings/"]

[tool.ruff.lint]
extend-select = ["E501", "UP", "D", "I", "PGH", "RUF", "T20"]
ignore = ["D203", "D212"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["D104"]
"**/{tests,migrations}/*" = ["D"]

[tool.ty.rules]
unresolved-import = "warn"

[tool.ty.src]
exclude = ["**/typings/"]
