"""
This type stub file was generated by pyright.
"""

from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker

"""Database connection logic."""
def sqla_session_maker(sqla_engine: AsyncEngine) -> async_sessionmaker[AsyncSession]:
    ...

