"""
This type stub file was generated by pyright.
"""

from sqlalchemy.orm import DeclarativeBase, Mapped

"""Manga database ORM models."""
class Base(DeclarativeBase):
    """Base ORM model."""
    ...


class Manga(Base):
    """Manga ORM model."""
    __tablename__: str = ...
    id: Mapped[int] = ...
    chapters: Mapped[list[Chapter]] = ...


class Chapter(Base):
    """Manga chapter model."""
    __tablename__: str = ...
    id: Mapped[int] = ...
    manga_id: Mapped[int] = ...
    manga: Mapped[Manga] = ...


