"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import override
from sqlalchemy.ext.asyncio import AsyncSession
from manga.application.dto import MangaDTO
from manga.application.repository import MangaRepository

"""Manga infrastructure repository module."""
@dataclass
class MangaRepositoryImpl(MangaRepository):
    """Implementation manga repository interface."""
    _session: AsyncSession
    def __init__(self, session: AsyncSession) -> None:
        ...
    
    @override
    async def get_by_id(self, manga_id: int) -> MangaDTO | None:
        ...
    
    @override
    async def get_all(self) -> list[MangaDTO]:
        ...
    


