"""
This type stub file was generated by pyright.
"""

from typing import override
from sqlalchemy.ext.asyncio import AsyncSession
from manga.application.dto import MangaDTO
from manga.application.repository import MangaRepository

"""Manga infrastructure repository module."""
class SQLARepository:
    """SQLAlchemy base repository."""
    _session: AsyncSession
    def __init__(self, session: AsyncSession) -> None:
        ...
    
    async def create(self, instance: object) -> object:
        """Save SQLAlchemy ORM model."""
        ...
    


class MangaRepositoryImpl(MangaRepository, SQLARepository):
    """Implementation manga repository interface."""
    @override
    async def get_by_id(self, manga_id: int) -> MangaDTO | None:
        ...
    
    @override
    async def get_all(self, limit: int = ..., offset: int = ...) -> list[MangaDTO]:
        ...
    


