"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager
from sqlalchemy.ext.asyncio import AsyncSession
from manga.application.repository import MangaRepository
from manga.application.service import MangaService
from manga.presentation.api.di import GlobalDependencies

"""Database dependency injection utilities."""
@asynccontextmanager
async def sqla_session_ctx(global_dependencies: GlobalDependencies) -> AsyncGenerator[AsyncSession]:
    """Return SQLAlchemy async session from `Robyn` DI."""
    ...

@asynccontextmanager
async def manga_repository_ctx(global_dependencies: GlobalDependencies) -> AsyncGenerator[MangaRepository]:
    """Return Manga persistence repository with SQLAlchemy session."""
    ...

@asynccontextmanager
async def manga_service_ctx(global_dependencies: GlobalDependencies) -> AsyncGenerator[MangaService]:
    """Return Manga application-layer service with implemented repository."""
    ...

