name: Continuous Integration checks

on: [push, pull_request]

jobs:
  uv-ci:
    name: python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13.5"
    defaults:
      run:
        working-directory: apps/backend

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.2"

      - name: Install the projects
        run: |
          export UV_PROJECT_ENVIRONMENT="${pythonLocation}"
          uv sync --locked --all-extras --dev

      - name: Run tests
        run: python -m pytest

      - name: Run basedpyright
        run: python -m basedpyright
