name: Continuous Integration checks

on: [push, pull_request]

jobs:
  uv-ci:
    name: python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13.5"
    defaults:
      run:
        working-directory: apps/backend

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.2"
          enable-cache: true

      - name: Install the projects
        run: |
          uv sync --locked --all-extras --dev
          export PATH="$(pwd)/.venv/bin:$PATH"

      - name: Run tests
        run: uvx pytest

      - name: Run basedpyright
        run: uvx basedpyright@1.31.0
